apiVersion: v1
kind: Service
metadata:
  name: xwiki-service
  namespace: xwiki-http
spec:
  selector:
    app: xwiki-http
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
